version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "https://s3-ap-southeast-1.amazonaws.com/stagevoting.propyoda.com"
    BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli@8.2.2
      - npm install
  build:
    commands:
      - echo Build started
      - ng build --prod --aot=false --build-optimizer=false
artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no
